### ISSUE TITLE
很不错,很符合我的口味

### ISSUE THREAD

**Issue by xiamuguizhi** [SomeBottle/BottleBlog#1]
我就喜欢这种简单的不能再简单的博客程序了

不用数据库的博客 用的不下超过20几种

**Comment by SomeBottle** [comment]
这个项目是我第一次写博客的作品，现在停止维护了，取而代之的是另一个OBottle.   
另外最近有意开坑全静态博客....感谢支持~

**Comment by xiamuguizhi** [comment]
@SomeBottle 全静态博客，哈哈哈  我也想过 直接生成html 文件

**Comment by SomeBottle** [comment]
@xiamuguizhi 全静态博客已经完工了，默认使用的是BottleBlog这个项目的主题，感谢支持~   
项目地址:  https://github.com/SomeBottle/-O-    
示例： https://bottle.moe

**Comment by xiamuguizhi** [comment]
@SomeBottle 抱歉 现在才看到 邮箱邮件太多了很多没关注到 我现在用的是minicms

**Comment by SomeBottle** [comment]
> @SomeBottle 抱歉 现在才看到 邮箱邮件太多了很多没关注到 我现在用的是minicms

哈哈，真的有点久远了

**Comment by xiamuguizhi** [comment]
@SomeBottle   我终于实现了，自己的无数据库博客系统了，太难了，真么多年 哈哈，因为还是没学会 html php 代码还是百度来的 哈哈。

地址：https://xn--qpru0x.cn/   

确实，我记得那时候你还没上大学  还去过你博客好多次，后面就没怎么联系了，好像忘记网址了。

**Comment by SomeBottle** [comment]
> @SomeBottle 我终于实现了，自己的无数据库博客系统了，太难了，真么多年 哈哈，因为还是没学会 html php 代码还是百度来的 哈哈。
> 
> 地址：https://xn--qpru0x.cn/
> 
> 确实，我记得那时候你还没上大学 还去过你博客好多次，后面就没怎么联系了，好像忘记网址了。

不容易哇，坚持写完就是最棒的啦~  
说回来我也想再重新写一个静态博客生成器了，折腾不止哇

**Comment by xiamuguizhi** [comment]
@SomeBottle 哈哈，我是瞎折腾，代码都是百度的，不像现在很多静态博客 都上什么vue xxx 一大堆代码，安装都懵逼半天 哈哈。

强啊！！可以！！新的静态博客生成器 ！！
